#' Parse export files from Beckman LS13 320
#'
#' This function handles the export files generated by a Beckman-Coulter LS13 320 Particle Size Analyser and parses them into tidy dataframes.
#'
#' @param pattern Regex file pattern to filter files in input directory. Default pattern is ".+\\.\\$ls\\.txt"
#'
#' @return A list of dataframes with one dataframe per paragraph in the well-structured export text files.
#' @export

read_beckman_LS13320 <- function(path = ".", pattern  = ".+\\.\\$ls\\.txt") {
  files <- dir(path, pattern)

  GSdata <-
    purrr::map(files, validateFile) %>%
    purrr::transpose() %>%
    purrr::map(bind_rows)
  return(GSdata)
}

validateFile <- function(fileName) {
  con <- file(fileName, "r")
  textLines <- readLines(con)
  close(con)

  startPattern <-
    c("LS\t|From\t|Particle Diameter\t|Channel Diameter \\(Lower\\)\t")

  startVec <- textLines %>%
    stringr::str_which(startPattern)

  if (is_empty(startVec) |
      length(startVec) != 4)
    stop("Invalid raw data: Sections not found")


  startEndList <- list(startVec, endVec)

  funs <-
    list(extractParams,
         extractStats,
         extractInterps,
         extractChannels)

  datatbl <- purrr::invoke_map(funs, fileName, startEndList)
  return(datatbl)
}

extractParams <- function(fileName, startEndList) {
  startPos <- startEndList[[1]][1]
  endPos <- startEndList[[2]][1]

  paramstbl <-
    tibble::tribble(
      ~ UID,
      ~ FileID,
      ~ SampleID,
      ~ Operator,
      ~ Barcode,
      ~ Comment1,
      ~ Comment2,
      ~ Instrument,
      ~ Run,
      ~ StartTime,
      ~ RunLength,
      ~ OpticalModel,
      ~ Obscuration,
      ~ PIDSObscuration,
      ~ ObscurationWarn,
      ~ Serial
    )

  paramstbl[1,] <-
    readr::read_tsv(
      fileName,
      skip = startPos,
      n_max = endPos - startPos,
      col_names = FALSE,
      col_types = cols(.default = "c")
    ) %>%
    t() %>%
    .[2,]
  paramstbl <- paramstbl %>%
    dplyr::mutate_at(vars(UID), str_replace_all, fixed(".$ls"), "") %>%
    dplyr::mutate(
      StartDepth = as.numeric(stringr::str_split(SampleID, "-")[[1]][1]),
      EndDepth = as.numeric(stringr::str_split(SampleID, "-")[[1]][2]),
      MeanDepth = (StartDepth + EndDepth) / 2
    )
  return(paramstbl)
}

extractStats <- function(fileName, startEndList) {
  startPos <- startEndList[[1]][2]
  endPos <- startEndList[[2]][2]

  statstbl <-
    tibble::tribble(
      ~ From,
      ~ To,
      ~ Volume,
      ~ Mean,
      ~ Median,
      ~ MeanMedianRatio,
      ~ Mode,
      ~ SD,
      ~ Variance,
      ~ CV,
      ~ Skewness
    )
  statstbl[1,] <-
    readr::read_tsv(
      fileName,
      skip = startPos - 1,
      n_max = endPos - startPos,
      col_names = FALSE,
      col_types = cols(.default = "c")
    ) %>%
    t() %>%
    .[2,]

  statstbl <- statstbl %>%
    tibble::add_column(UID = str_replace(fileName, fixed(".$ls.txt"), ""), .before = 1) %>%
    dplyr::mutate_at(vars(-UID), as.numeric)
  return(statstbl)
}

extractInterps <- function(fileName, startEndList) {
  startPos <- startEndList[[1]][3]
  endPos <- startEndList[[2]][3]
  interptbl <-
    readr::read_tsv(
      fileName,
      skip = startPos - 1,
      n_max = endPos - startPos,
      col_types = cols(.default = "c")
    ) %>%
    dplyr::select("Particle Diameter", "Volume") %>%
    dplyr::rename("Di" = "Particle Diameter", "volp" = "Volume") %>%
    dplyr::slice(-c(1, 2)) %>%
    dplyr::mutate_all(as.numeric) %>%
    dplyr::filter(Di != 2000) %>%
    tibble::add_column(UID = str_replace(fileName, fixed(".$ls.txt"), ""), .before = 1) %>%
    dplyr::mutate(
      qual1 = dplyr::case_when(
        .$Di == 0.04 ~ "clay",
        .$Di >= 4 &
          .$Di <= 31 ~ "silt",
        .$Di >= 32 &
          .$Di < 1000 ~ "sand",
        .$Di >= 1000 ~ "other"
      ),
      qual2 = dplyr::case_when(
        .$Di == 0.04 ~ "",
        .$Di == 4 ~ "very fine",
        .$Di == 8 ~ "fine",
        .$Di == 16 ~ "medium",
        .$Di == 31 ~ "coarse",
        .$Di == 62.5 ~ "very fine",
        .$Di == 125 ~ "fine",
        .$Di == 250 ~ "medium",
        .$Di == 500 ~ "coarse",
        .$Di == 1000 ~ ""
      )
    )
  return(interptbl)
}

extractChannels <- function(fileName, startEndList) {
  startPos <- startEndList[[1]][4]
  endPos <- startEndList[[2]][4]
  channelstbl <-
    readr::read_tsv(
      fileName,
      skip = startPos,
      n_max = endPos - startPos,
      col_types = cols(.default = "c")
    ) %>%
    dplyr::select("um", "Volume", matches("Number")) %>%
    dplyr::slice(-c(1)) %>%
    dplyr::mutate_all(as.numeric) %>%
    tibble::add_column(UID = str_replace(fileName, fixed(".$ls.txt"), ""), .before = 1) %>%
    dplyr::rename("lwr" = "um", "volp" = "Volume") %>%
    dplyr::filter(lwr != 2000) %>%
    dplyr::mutate(upr = c(unlist(.[2:length(.$lwr), "lwr"]), 2000), Di = sqrt(upr * lwr))
  return(channelstbl)
}
