#' Parse export files from Beckman LS13 320
#'
#' This function handles the export files generated by a Beckman-Coulter LS13 320 Particle Size Analyser and parses them into tidy dataframes. The function will return the parameter paragraph, the descriptive statistics paragraph, the interpolated particle size paragraph and the raw channel data paragraph or any subset of these if existing.
#'
#' @param path The path to the export files.
#' @param pattern Regular expression pattern to filter files in input directory. Default pattern is '.+\\.\\$ls\\.txt' and will filter *.$ls.txt files.
#'
#' @return A list of dataframes with one dataframe per paragraph contained in the well-structured LS13 320 export files.
#' @export

read_LS13320_export <-
    #Can the function be written so generally that it may work with other/all configurations of export files?
    function(path, pattern = ".+\\.\\$ls\\.txt") {
        files <- dir(path, pattern, full.names = TRUE)


        GSdata <-
            purrr::map(files, validateFile) %>% purrr::transpose() %>% purrr::map(dplyr::bind_rows)
        return(GSdata)
    }

validate_LS13320_export <- function(fileName) {
    con <- file(fileName, "r")
    textLines <- readLines(con)
    close(con)

    startPattern <-
        c("LS\t|From\t|Particle Diameter\t|Channel Diameter \\(Lower\\)\t")
    startVec <- textLines %>% stringr::str_which(startPattern)
    if (purrr::is_empty(startVec) | length(startVec) != 4)
        stop("Invalid raw data: Sections not found")
    endVec <- which(textLines == "") - 1L
    startEndList <- list(startVec, endVec)
    funs <-
        list(extractParams,
             extractStats,
             extractInterps,
             extractChannels)

    datatbl <- purrr::invoke_map(funs, fileName, startEndList)
    return(datatbl)
}

extractParams <- function(fileName, startEndList) {
    startPos <- startEndList[[1]][1]
    endPos <- startEndList[[2]][1]

    paramsvec_names <-
        c(
            "UID",
            "FileID",
            "SampleID",
            "Operator",
            "Barcode",
            "Comment1",
            "Comment2",
            "Instrument",
            "Run",
            "StartTime",
            "RunLength",
            "OpticalModel",
            "Obscuration",
            "PIDSObscuration",
            "ObscurationWarn",
            "Serial"
        )

    paramsvec <-
        readr::read_tsv(
            fileName,
            skip = startPos,
            n_max = endPos - startPos,
            col_names = FALSE,
            col_types = readr::cols(.default = "c")
        ) %>%
        t() %>%
        .[2, ]

    names(paramsvec) <- paramsvec_names

    paramstbl <- paramsvec %>%
        tibble::as_tibble_row() %>%
        dplyr::mutate_at(dplyr::vars(UID),
                         stringr::str_replace_all,
                         stringr::fixed(".$ls"),
                         "") %>%
        dplyr::mutate(
            StartDepth = as.numeric(stringr::str_split(SampleID, "-")[[1]][1]),
            EndDepth = as.numeric(stringr::str_split(SampleID, "-")[[1]][2]),
            MeanDepth = (StartDepth + EndDepth) / 2
        )
    return(paramstbl)
}

extractStats <- function(fileName, startEndList) {
    startPos <- startEndList[[1]][2]
    endPos <- startEndList[[2]][2]

    statsvec_names <-
        c(
            "From",
            "To",
            "Volume",
            "Mean",
            "Median",
            "MeanMedianRatio",
            "Mode",
            "SD",
            "Variance",
            "CV",
            "Skewness"
        )

    statsvec <-
        readr::read_tsv(
            fileName,
            skip = startPos - 1,
            n_max = endPos - startPos,
            col_names = FALSE,
            col_types = readr::cols(.default = "c")
        ) %>%
        t() %>%
        .[2,]

    names(statsvec) <- statsvec_names

    statstbl <- statsvec %>%
        tibble::as_tibble_row() %>%
        tibble::add_column(
            UID = stringr::str_extract(fileName, "(?<=\\/)\\w*(?=\\.\\$ls\\.txt)"),
            .before = 1
        ) %>% dplyr::mutate_at(dplyr::vars(-UID),
                               as.numeric)
    return(statstbl)
}

extractInterps <- function(fileName, startEndList) {
    startPos <- startEndList[[1]][3]
    endPos <- startEndList[[2]][3]
    interptbl <-
        readr::read_tsv(
            fileName,
            skip = startPos - 1,
            n_max = endPos - startPos,
            col_types = readr::cols(.default = "c")
        ) %>% dplyr::select("Particle Diameter",
                            "Volume") %>% dplyr::rename(Di = "Particle Diameter", volp = "Volume") %>% dplyr::slice(-c(1, 2)) %>% dplyr::mutate_all(as.numeric) %>%
        dplyr::filter(Di != 2000) %>% tibble::add_column(UID = stringr::str_replace(fileName, fixed(".$ls.txt"), ""),
                                                         .before = 1) %>% dplyr::mutate(
                                                             qual1 = dplyr::case_when(
                                                                 .$Di ==
                                                                     0.04 ~ "clay",
                                                                 .$Di >= 4 &
                                                                     .$Di <= 31 ~ "silt",
                                                                 .$Di >= 32 &
                                                                     .$Di < 1000 ~ "sand",
                                                                 .$Di >= 1000 ~ "other"
                                                             ),
                                                             qual2 = dplyr::case_when(
                                                                 .$Di ==
                                                                     0.04 ~ "",
                                                                 .$Di == 4 ~ "very fine",
                                                                 .$Di == 8 ~ "fine",
                                                                 .$Di == 16 ~ "medium",
                                                                 .$Di == 31 ~ "coarse",
                                                                 .$Di == 62.5 ~ "very fine",
                                                                 .$Di ==
                                                                     125 ~ "fine",
                                                                 .$Di == 250 ~ "medium",
                                                                 .$Di == 500 ~ "coarse",
                                                                 .$Di == 1000 ~ ""
                                                             )
                                                         )
    return(interptbl)
}

extractChannels <- function(fileName, startEndList) {
    startPos <- startEndList[[1]][4]
    endPos <- startEndList[[2]][4]
    channelstbl <-
        readr::read_tsv(
            fileName,
            skip = startPos,
            n_max = endPos - startPos,
            col_types = readr::cols(.default = "c")
        ) %>% dplyr::select("um",
                            "Volume", dplyr::matches("Number")) %>% dplyr::slice(-c(1)) %>% dplyr::mutate_all(as.numeric) %>% tibble::add_column(UID = stringr::str_replace(fileName,
                                                                                                                                                                            fixed(".$ls.txt"), ""),
                                                                                                                                                 .before = 1) %>% dplyr::rename(lwr = "um", volp = "Volume") %>% dplyr::filter(lwr != 2000) %>% dplyr::mutate(upr = c(unlist(.[2:length(.$lwr),
                                                                                                                                                                                                                                                                               "lwr"]), 2000), Di = sqrt(upr * lwr))
    return(channelstbl)
}
